### ISSUE TITLE
How often did we have case when one run has several different ref genomes?

### ISSUE THREAD

**Issue by anatolydryga** [BushmanLab/intSiteCaller#11]
monkey and human on the same run?
or hg18 and hg19 on the same run?

**Comment by esherm** [comment]
We almost never have different organisms on the same run and thus far haven't had different freezes on the same run. 

We might, however, want to process the same sequences with two different reference genomes right off the bat. For example, old 454 data may stay permanently at hg18 and new data is processed and stored as hg19. We might want to simultaneously process future runs with **both** hg18/19 so that we can compare results to 454 data and to new data.

**Comment by esherm** [comment]
Our priming scheme does completely support different organisms on the same run, we just haven't historically utilized that flexibility. We might want to utilize that flexibility in the future, but it would be the exception rather than the norm.

**Comment by anatolydryga** [comment]
If we need to proccess multiple genomes on the same run we can use non-standard `sampleInfo.tsv`
and non-standard `processingParams.tsv`,
we add column `refGenome` to `sampleInfo.tsv` and remove this column from `processingParams.tsv`.

**Comment by anatolydryga** [comment]
resloved see Readme.md
