### ISSUE TITLE
what is linker Common for the case when linker does not have NNNN?

### ISSUE THREAD

**Issue by anatolydryga** [BushmanLab/intSiteCaller#4]

**Comment by esherm** [comment]
This information can be provided by the wet lab technicians, although for the purposes of removing read-through of the linker from the LTR read, it actually doesn't matter.  We can just take the last 15bp of the linker and reverse-complement it, even if the 'true' linker_common sequence is less than 15bp.  This works because each sample (i.e. unique linker) is processed independently.  Any read-through in that sample is practically gauranteed to have the reverse compliment of the unique linker sequence assigned to that sample as well.  A primerID linker i.e. one with N's in it doesn't have that same guarantee, as every single molecule within that given sample will have a different primerID.  We have no way of knowing what to expect when we're looking for read-through.
